name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v7

      - name: Check API key
        env:
          PUBLIC_FORM_API_KEY: ${{ secrets.PUBLIC_FORM_API_KEY }}
        run: |
          if [ -z "$PUBLIC_FORM_API_KEY" ]; then
            echo "❌ PUBLIC_FORM_API_KEY IS EMPTY"
            exit 1
          else
            echo "✅ PUBLIC_FORM_API_KEY is set"
          fi

      - name: Install, build, and upload your site
        uses: withastro/action@v6
        env:
          PUBLIC_FORM_API_KEY: ${{ secrets.PUBLIC_FORM_API_KEY }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
